### ISSUE TITLE
Integration with Stripe

### ISSUE THREAD

**Issue by tpharaoh** [firebed/aade-mydata#7]
Awesome package! None of the services my accountant suggested were in English, so I was really happy to find this. I am using stripe, with 2 invoice series. 

I guess there isn't a way to automate stripe <> AADE because of all the custom stuff inside AADE. Or have you heard of someone using your package that way?

**Comment by idimopoulos** [comment]
The package is not integrating with any payment gateway nor it automatically generates any data according to the payment authority. You are responsible of generating the data as they are not related with the payment gateway, rather than with AADE parameters, which is mainly the nature of the transaction, the goods, and the identity of the parties.
Thus, you would not have an integration with Stripe, rather than retrieving the results from them, and when successful, construct the XML and provide it to AADE. That XML will not have any information about Stripe other than maybe the date of the payment.

**Comment by tpharaoh** [comment]
I got that. Thanks, yea, I was just curious if you knew someone already integrating.  Anyway this is probably just what I needed. thanks for the great work!

**Comment by sapountzis** [comment]
Awesome work!

I didn't want to open a new issue so I will ask it here: Do you know which payment method corresponds to stripe payment? I believe it is NOT the POS/e-POS flow because there no ECR token / Provider Signature is returned from Stripe.

And in general if you know which payment type corresponds to online payments via debit/credit card

Thanks

**Comment by firebed** [comment]
There aren't any clear instructions. I generally prefer to use "Επαγγελματικός λογαριασμός πληρωμών ημεδαπής" for wire transfers and "Web banking" for payments through Stripe,  PayPal etc.

POS/ePOS requires ECR token signature and must be used if you or client owns a terminal like POS machine for processing payments.

**Comment by sapountzis** [comment]
Thanks a lot for the answer.
And can I just use this API directly to myDATA as a business without going through an approved [provider](https://www.aade.gr/mydata/parohoi-ypiresion-ilektronikis-timologisis)?

**Comment by firebed** [comment]
Yes you can, except for retail invoices (αποδείξεις λιανικής - πιστωτικά λιανικής). Although in the current implementation it possible to issue retail invoices through ERP ΑΑΔΕ might reject them in the future. So if you intend to issue retail invoices a provider is right way to go.
